# Generated by Django 4.2.6 on 2025-06-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['timestamp']},
        ),
    ]
