# Generated by Django 4.2.6 on 2025-06-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_communication_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buyer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
    ]
