# Generated by Django 4.2.6 on 2025-06-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_date_completed_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='quantity_after_movement',
            field=models.IntegerField(blank=True, help_text='Inventory quantity after this movement occurred', null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('addition', 'Stock Added'), ('removal', 'Stock Removed'), ('adjustment', 'Stock Adjusted'), ('transfer', 'Stock Transferred'), ('sale', 'Sale to Customer'), ('purchase', 'Purchase from Supplier')], max_length=20),
        ),
    ]
