export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_REQUEST = 'USER_LOADED_REQUEST';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_REQUEST = 'GOOGLE_AUTH_REQUEST';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

//cart data types
export const CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const  CART_DATA_SUCCESS = "CART_DATA_SUCCESS";
export const CART_DATA_FAIL = "CART_DATA_FAIL";
export const COOKIE_CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const COOKIE_CART_DATA_SUCCESS = "COOKIE_CART_DATA_SUCCESS";
export const COOKIE_CART_DATA_FAIL = "COOKIE_CART_DATA_FAIL";

//cart data manipulation types
export const ORDERED_ITEM_SUCCESS = "ORDERED_ITEM_SUCCESS"
export const ORDERED_ITEM_FAIL = "ORDERED_ITEM_FAIL"

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL"

export const PRODUCTS_DATA_REQUEST = "PRODUCTS_DATA_REQUEST"
export const PRODUCTS_DATA_SUCCESS = "PRODUCTS_DATA_SUCCESS"
export const PRODUCTS_DATA_FAIL = "PRODUCTS_DATA_FAIL"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

export const PRODUCTS_FILTERED_REQUEST = "PRODUCTS_FILTERED_REQUEST"
export const PRODUCTS_FILTERED_SUCCESS = 'PRODUCTS_FILTERED_SUCCESS';
export const PRODUCTS_FILTERED_FAIL = 'PRODUCTS_FILTERED_FAIL';

export const RESET_PRODUCTS_SUCCESS = "RESET_PRODUCTS_SUCCESS"
export const RESET_PRODUCTS_FAIL = "RESET_PRODUCTS_FAIL"

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_FAIL = "SEARCH_PRODUCTS_FAIL"

