# Generated by Django 4.2.6 on 2025-06-01 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['activation_token'], name='accounts_or_activat_872d0d_idx'),
        ),
    ]
