# Generated by Django 4.2.6 on 2025-06-02 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_activation_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_organiz_7a60e0_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('buyer', 'Buyer Organization'), ('supplier', 'Supplier Organization'), ('both', 'Buyer and Supplier Organization'), ('internal', 'Internal Organization')], default='buyer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='accounts_or_organiz_fc06fd_idx'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='buyer_organization',
            field=models.ForeignKey(limit_choices_to={'organization_type__in': ['buyer', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='buying_relationships', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='supplier_organization',
            field=models.ForeignKey(limit_choices_to={'organization_type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='supplying_relationships', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['buyer_organization', 'supplier_organization'], name='accounts_or_buyer_o_e30bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['status'], name='accounts_or_status_e0bd2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrelationship',
            unique_together={('buyer_organization', 'supplier_organization')},
        ),
    ]
